// CONNECTION STATUS
export const UPDATE_CONNECTION_STATUS = '@@CONNECTION/UPDATE_CONNECTION_STATUS';

// ENCRYPT POST
export const ENCRYPT_POST_INIT    = 'ENCRYPT_POST_INIT';
export const ENCRYPT_POST_REQUEST = 'ENCRYPT_POST_REQUEST';
export const ENCRYPT_POST_SUCCESS = 'ENCRYPT_POST_SUCCESS';
export const ENCRYPT_POST_FAILURE = 'ENCRYPT_POST_FAILURE';

// DECRYPT
export const CHECK_PAGE = 'CHECK_PAGE';

export const DECRYPT_POST_REQUEST = 'DECRYPT_POST_REQUEST';
export const DECRYPT_POST_SUCCESS = 'DECRYPT_POST_SUCCESS';
export const DECRYPT_POST_FAILURE = 'DECRYPT_POST_FAILURE';


// SETTINGS
export const SETTINGS_REQUEST = 'SETTINGS_REQUEST';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_FAILURE = 'SETTINGS_FAILURE';
