export const LOGIN_REQUEST = '@@jwt/LOGIN_REQUEST';
export const LOGIN_SUCCESS = '@@jwt/LOGIN_SUCCESS';
export const LOGIN_FAILURE = '@@jwt/LOGIN_FAILURE';

export const LOGOUT        = '@@jwt/LOGOUT';

export const SIGNUP_REQUEST = '@@jwt/SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = '@@jwt/SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = '@@jwt/SIGNUP_FAILURE';

export const TOKEN_REQUEST  = '@@jwt/TOKEN_REQUEST';
export const TOKEN_RECEIVED = '@@jwt/TOKEN_RECEIVED';
export const TOKEN_FAILURE  = '@@jwt/TOKEN_FAILURE';

// ----- SEARCH ----------

export const SEARCH_QUERY_REQUEST = 'SEARCH/QUERY_REQUEST';
export const SEARCH_QUERY_SUCCESS = 'SEARCH/QUERY_SUCCESS';
export const SEARCH_QUERY_FAILURE = 'SEARCH/QUERY_FAILURE';

// ------ DATA_LOADER ----------

export const DATA_LOADER_LIST_REQUEST = '@@DATA_LOADER/LIST_REQUEST';
export const DATA_LOADER_LIST_UPDATE_REQUEST = '@@DATA_LOADER/UPDATE_LIST_REQUEST';
export const DATA_LOADER_LIST_SUCCESS = '@@DATA_LOADER/LIST_SUCCESS';
export const DATA_LOADER_LIST_FAILURE = '@@DATA_LOADER/LIST_FAILURE';


export const DATA_LOADER_DETAIL_REQUEST = '@@DATA_LOADER/DETAIL_REQUEST';
export const DATA_LOADER_DETAIL_UPDATE = '@@DATA_LOADER/DETAIL_UPDATE';
export const DATA_LOADER_DETAIL_SUCCESS = '@@DATA_LOADER/DETAIL_SUCCESS';
export const DATA_LOADER_DETAIL_FAILURE = '@@DATA_LOADER/DETAIL_FAILURE';

export const DATA_LOADER_UPLOAD_REQUEST = '@@DATA_LOADER/UPLOAD_REQUEST';
export const DATA_LOADER_UPLOAD_SUCCESS = '@@DATA_LOADER/UPLOAD_SUCCESS';
export const DATA_LOADER_UPLOAD_FAILURE = '@@DATA_LOADER/UPLOAD_FAILURE';

export const DATA_LOADER_DELETE_REQUEST = '@@DATA_LOADER/DELETE_REQUEST';
export const DATA_LOADER_DELETE_SUCCESS = '@@DATA_LOADER/DELETE_SUCCESS';
export const DATA_LOADER_DELETE_FAILURE = '@@DATA_LOADER/DELETE_FAILURE';

export const TYPEAHEAD_LIST_REQUEST = '@@TYPEAHEAD/LIST_REQUEST';
export const TYPEAHEAD_LIST_UPDATE_REQUEST = '@@TYPEAHEAD/UPDATE_LIST_REQUEST';
export const TYPEAHEAD_LIST_SUCCESS = '@@TYPEAHEAD/LIST_SUCCESS';
export const TYPEAHEAD_LIST_FAILURE = '@@TYPEAHEAD/LIST_FAILURE';

export const SEARCH_COMPONENT = "@@SEARCH/COMPONENT";

// BUDGETS
export const BUDGETS_MAKE_FINANCES = "@@BUDGETS/MAKE_FINANCES";

// FINANCES
export const FINANCES_CLEAR_ALL = "@@FINANCES/CLEAR_ALL";

// FORMS

export const FORMS_SHOW = "@@FORMS/SHOW";
export const FORMS_HIDE = "@@FORMS/HIDE";




